### ISSUE TITLE
Missing functionality to link third party dependencies

### ISSUE THREAD

**Issue by SirPounce** [Tolc-Software/bootstrap-tolc-cmake#5]
given a project structure

- bootstrap-tolc-cmake
- sample_cpp_project
   - third_party
       - dependency
          - CMakeLists.txt
   - CMakeLitsts.txt
- CMakeLists.txt

Building using using this CMakeLists.txt in root
```
cmake_minimum_required(VERSION 3.15)

project(bootstrap-tolc-cmake)

# Some library to generate bindings from
add_subdirectory(sample_cpp_project)

include(FetchContent)
FetchContent_Declare(
  tolc_bootstrap
  GIT_REPOSITORY https://github.com/Tolc-Software/bootstrap-tolc-cmake
  GIT_TAG        main
)

FetchContent_MakeAvailable(tolc_bootstrap)
# Download and uses find_package to locate tolc
get_tolc()

# This function comes from the tolc package itself
# Creates the target bootstrap_python that can be imported and used from python
tolc_create_translation(
  # Target to translate from
  TARGET sample_cpp_project
  # Language to target
  LANGUAGE python
  # Where to put the bindings
  OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/python-bindings
)
```

Works fine until running cmake --build build, where it can not find the third_party dependency

U can reproduce using this as sample cpp project:
https://github.com/daedric/httpp just switch out the sample_cpp_project to httpp in the cmakelists file

**Comment by srydell** [comment]
Hi! Thank you for highlighting this. There seems to be a compiler error while building daedric/httpp, but the error with the project layout should be fixed now. You should be able to just rebuild to get the latest release of tolc. If you have any other issues or feel that this is not closed properly, feel free to open a new issue.
